# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: linux-64
@EXPLICIT
https://repo.anaconda.com/pkgs/main/linux-64/blas-1.0-mkl.tar.bz2
https://conda.anaconda.org/anaconda/linux-64/ca-certificates-2018.03.07-0.tar.bz2
https://conda.anaconda.org/soumith/linux-64/cuda80-1.0-0.tar.bz2
https://repo.anaconda.com/pkgs/free/linux-64/cudatoolkit-8.0-3.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/intel-openmp-2019.0-118.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/libgcc-ng-8.2.0-hdf63c60_1.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/libgfortran-ng-7.3.0-hdf63c60_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/libstdcxx-ng-8.2.0-hdf63c60_1.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/bzip2-1.0.6-h14c3975_5.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/expat-2.2.6-he6710b0_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/gmp-6.1.2-h6c8ec71_1.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/icu-58.2-h9c2bf20_1.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/jpeg-9b-h024ee3a_2.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/libffi-3.2.1-hd88cf55_4.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/libiconv-1.15-h63c8f33_5.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/libsodium-1.0.16-h1bed415_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/libuuid-1.0.3-h1bed415_2.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/libxcb-1.13-h1bed415_1.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/mkl-2018.0.3-1.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/ncurses-6.1-he6710b0_1.tar.bz2
https://conda.anaconda.org/anaconda/linux-64/openssl-1.1.1-h7b6447c_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/pcre-8.42-h439df22_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/xz-5.2.4-h14c3975_4.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/yaml-0.1.7-had09818_2.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/zlib-1.2.11-h7b6447c_3.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/glib-2.56.2-hd408876_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/libedit-3.1.20170329-h6b74fdf_2.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/libpng-1.6.35-hbc83047_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/libssh2-1.8.0-h1ba5d50_4.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/libtiff-4.0.9-he85c1e1_2.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/libxml2-2.9.8-h26e45fe_1.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/pandoc-1.19.2.1-hea2e7c5_1.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/readline-7.0-h7b6447c_5.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/rhash-1.3.6-h1ba5d50_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/tk-8.6.8-hbc83047_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/dbus-1.13.2-h714fa37_1.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/freetype-2.9.1-h8a8886c_1.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/gstreamer-1.14.0-hb453b48_1.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/libcurl-7.62.0-h20c2e04_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/sqlite-3.25.3-h7b6447c_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/fontconfig-2.13.0-h9420a91_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/gst-plugins-base-1.14.0-hbbd80ab_1.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/python-3.6.7-h0371630_0.tar.bz2
https://conda.anaconda.org/anaconda/linux-64/certifi-2018.10.15-py36_0.tar.bz2
https://conda.anaconda.org/anaconda/linux-64/joblib-0.13.0-py36_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/kiwisolver-1.0.1-py36hf484d3e_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/ninja-1.8.2-py36h6bb024c_1.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/numpy-base-1.15.4-py36h81de0dd_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/olefile-0.46-py36_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/pycparser-2.19-py36_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/pyparsing-2.3.0-py36_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/pytz-2018.7-py36_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/qt-5.6.3-h8bf5577_3.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/sip-4.18.1-py36hf484d3e_2.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/six-1.11.0-py36_1.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/tornado-5.1.1-py36h7b6447c_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/cffi-1.11.5-py36he75722e_1.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/cycler-0.10.0-py36_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/pillow-5.3.0-py36h34e0f95_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/pyqt-5.6.0-py36h22d08a2_6.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/python-dateutil-2.7.5-py36_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/setuptools-40.6.2-py36_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/wheel-0.32.3-py36_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/pip-18.1-py36_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/matplotlib-2.2.2-py36hb69df0a_2.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/mkl_fft-1.0.6-py36h7dd41cf_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/mkl_random-1.0.1-py36h4414c95_1.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/numpy-1.15.4-py36h1d66e8a_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/pandas-0.23.4-py36h04863e7_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/pyedflib-0.1.14-py36h7eb728f_3.tar.bz2
https://conda.anaconda.org/soumith/linux-64/pytorch-0.4.1-py36_cuda8.0.61_cudnn7.1.2_1.tar.bz2
https://conda.anaconda.org/anaconda/linux-64/scipy-1.1.0-py36hfa4b5c9_1.tar.bz2
https://conda.anaconda.org/anaconda/linux-64/scikit-learn-0.20.1-py36h4989274_0.tar.bz2
https://conda.anaconda.org/soumith/linux-64/torchvision-0.1.9-py36h7584368_1.tar.bz2
